// SPDX-FileCopyrightText: 2026 Kasa Panel contributors
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// SPDX-FileContributor: Drafted with AI assistance (Anthropic Claude);
// see docs/ai-bom.spdx.json for the AI usage declaration.

// Bundles the React sources into kasapanel/static/bundle.js.  The result
// is committed, so installing the daemon needs no Node at all; you only
// need this when you change something under frontend/src.

import { build, context } from 'esbuild';
import process from 'node:process';

const options = {
  entryPoints: ['src/main.jsx'],
  bundle: true,
  format: 'iife',
  target: ['es2020'],
  minify: true,
  legalComments: 'none',
  outfile: '../kasapanel/static/bundle.js',
  define: { 'process.env.NODE_ENV': '"production"' },
  banner: {
    js: '/* SPDX-License-Identifier: GPL-3.0-or-later AND MIT */\n'
      + '/* Generated by frontend/build.mjs; edit frontend/src instead. */\n'
      + '/* Bundles React and ReactDOM (MIT, Meta Platforms). */',
  },
};

if (process.argv.includes('--watch')) {
  const ctx = await context(options);
  await ctx.watch();
  console.log('watching frontend/src');
} else {
  await build(options);
  console.log('wrote kasapanel/static/bundle.js');
}
